name: New Docs Version

on:
  pull_request:
    types:
      - closed

jobs:
  next_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx_multiversion
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git config
        run: |
          git config user.email "ayah.ehab11@gmail.com"
          git config user.name "Aya Elsayed"
      - name: Create new tag
        if: contains(github.event.pull_request.labels.*.name, 'docs-version++')
        run: |
          ./create_tag.sh
      - name: Finishing
        run: |
          echo "done."
      # - name: Sphinx build
      #   run: |
      #     git worktree add _build gh-pages
      #     sphinx-multiversion doc _build
      # - name: Deploy docs
      #   run: |
      #     cd _build
      #     git add --all
      #     git commit -m "deploy documentation updates"
      #     git push origin gh-pages
