name: DIY Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme
      - name: Sphinx build
        run: |
          sphinx-build doc _build
          git worktree add _build gh-pages
          git add --all
          git commit -m "deploy documentation updates"
          git push origin gh-pages
          git worktree remove _build
